### ISSUE TITLE
IE 11 support

### ISSUE THREAD

**Issue by markusguenther** [jonnitto/Jonnitto.PrettyEmbedHelper#1]
**Describe the bug**
Tested the package in combination with the package jonnitto/prettyembedyoutube
The package javascript throws some errors in the IE 11.

Saw that my initial error with the `const`inside the main.js already has been solved.
I did not understand how the public assest will be generated. Therefore just an issue instead of a PR ;)

**To Reproduce**
Just load a side with the included Main.js in the IE 11.

**Expected behavior**
No errors in the IE 11

**Screenshots**
<img width="455" alt="Bildschirmfoto 2019-10-06 um 20 19 28" src="https://user-images.githubusercontent.com/1014126/66273761-33d72200-e877-11e9-9ff4-b255c494a05c.png">

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser IE 11
- Version 1.0.3

**Comment by jonnitto** [comment]
Should be closed with version [1.0.4](https://github.com/jonnitto/Jonnitto.PrettyEmbedHelper/releases/tag/1.0.4)
