### ISSUE TITLE
GdprMessage not working

### ISSUE THREAD

**Issue by rolandschuetz** [jonnitto/Jonnitto.PrettyEmbedHelper#4]
**Describe the bug**
The message is never set.

`Jonnitto.PrettyEmbedVimeo:Component.Vimeo` uses `gdprMessage = Jonnitto.PrettyEmbedHelper:GdprMessage`, which is already false.

To fix this, the `Jonnitto.PrettyEmbedHelper:GdprMessage` key should be `value`instead of `gdprMessage`, see https://github.com/jonnitto/Jonnitto.PrettyEmbedHelper/blob/master/Resources/Private/Fusion/Helper/GdprMessage.fusion#L2

**Comment by jonnitto** [comment]
Sorry, I didn't saw this. This is fixed in https://github.com/jonnitto/Jonnitto.PrettyEmbedHelper/releases/tag/2.3.1
